project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"
    - "!/poster/"

website:
  title: SFU Summer School 2024
  image: /img/sfudrac_logo.png
  favicon: /img/sfu_favicon.png
  site-url: https://rcss24.netlify.app/
  repo-url: https://github.com/WestDRI/rcss24
  page-navigation: true
  page-footer:
    center:
      - text: About
        href: about.qmd
      - text: Calendar
        href: calendar.qmd
        aria-label: WestDRI training calendar
      - text: Newsletter
        href: newsletter.qmd
        aria-label: WestDRI Newsletter
      - href: contact.qmd
        aria-label: WestDRI Contact
      - text: Wiki
        href: https://docs.alliancecan.ca/wiki/Technical_documentation
    right:
      - icon: github
        href: https://github.com/WestDRI
        aria-label: WestDRI GitHub
      - icon: youtube
        href: https://www.youtube.com/channel/UCfgds4Qf7VFOv4ORRvFFmhw
        aria-label: WestDRI YouTube
  navbar:
    background: light
    logo: /img/sfudrac_logo.png
    logo-alt: "SFU & DRAC logos"
    title: false
    left:
      - text: Bash
        href: bash.qmd
      - text: HPC
        href: hpc.qmd
      - text: Git
        href: git.qmd
      - text: Intro to Python
        href: pythonintro.qmd
      - text: Scientific Python
        href: pythonscientific.qmd
      - text: High-performance Python
        href: pythonhpc.qmd
  sidebar:
    - id: bash
      contents:
        - section:
          contents:
            - bash/index.qmd
    - id: hpc
      contents:
        - section:
          contents:
            - hpc/index.qmd
    - id: r_intro
      contents:
        - section:
          contents:
            - r_intro/index.qmd
        - text: <em><b>Getting started with R</b></em>
          href: r_intro/index.qmd
          contents: 
            - text: Running R for this course
              href: r_intro/run_r_intro.qmd
            - text: "R: why and for whom?"
              href: r_intro/why.qmd
            - text: First steps in R
              href: r_intro/basics.qmd
            - text: Packages
              href: r_intro/packages.qmd
            - text: Data types and structures
              href: r_intro/data_structure.qmd
            - text: Indexing
              href: r_intro/indexing.qmd
            - text: Function definition
              href: r_intro/functions.qmd
            - text: Control flow
              href: r_intro/control_flow.qmd
            - text: Introduction to the tidyverse
              href: r_intro/tidyverse.qmd
            - text: Plotting
              href: r_intro/plotting.qmd
            - text: Publishing
              href: r_intro/publishing.qmd
            - text: Resources
              href: r_intro/resources.qmd
    - id: r_parallel
      contents:
        - section:
          contents:
            - r_parallel/index.qmd
        - text: <b><em>Parallel R</em></b>
          href: r_parallel/index.qmd
          contents:
            - text: SSH login
              href: r_parallel/run_r_hpc.qmd
            - text: R on HPC clusters
              href: r_parallel/clusters.qmd
            - text: Measuring performance
              href: r_parallel/performance.qmd
            - text: Optimizations
              href: r_parallel/optimizations.qmd
            - text: Memory management
              href: r_parallel/memory.qmd
            - text: Types of parallelism
              href: r_parallel/parallel_types.qmd
            - text: Parallel loops
              href: r_parallel/parallel_loops.qmd
            - text: Data on HPC clusters
              href: r_parallel/data.qmd
            - text: Partitioning data
              href: r_parallel/partition.qmd
            - text: Writing C++ in R with Rcpp
              href: r_parallel/rcpp.qmd
            - text: Resources for HPC in R
              href: r_parallel/resources_hpc.qmd
    - id: julia
      contents:
        - section:
          contents:
            - julia/index.qmd
    - id: ml
      contents:
        - section:
          contents:
            - ml/index.qmd
        - text: <b><em>DL with PyTorch</em></b>
          href: ml/index.qmd
          contents: 
            - text: Introduction
              href: ml/intro.qmd
            - text: Which framework to choose?
              href: ml/choosing_frameworks.qmd
            - text: High-level frameworks
              href: ml/high_level_frameworks.qmd
            - text: Introduction to NN
              href: ml/nn.qmd
            - text: The PyTorch API
              href: ml/pytorch.qmd
            - text: PyTorch tensors
              href: ml/tensors.qmd
            - text: Automatic differentiation
              href: ml/autograd.qmd
            - text: Workflow
              href: ml/workflow.qmd
            - text: Creating checkpoints
              href: ml/checkpoints.qmd
            - text: "Example: the MNIST"
              href: ml/mnist.qmd
            - text: ML on production clusters
              href: ml/hpc.qmd
            - text: Resources
              href: ml/resources.qmd
    - id: scivis
      contents:
        - section:
          contents:
            - scivis/index.qmd

format:
  html:
    toc: true
    toc-title: "<em>On this page:</em>"
    toc-depth: 5
    theme:
      light: [cosmo, theme.scss]
    css: styles.css
    link-external-newwindow: true
    reference-location: margin
    fig-cap-location: margin

execute:
  freeze: auto
  cache: true
  error: true
  echo: true
