project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"
    - "!/poster/"

website:
  title: SFU Summer School 2024
  image: /img/sfudrac_logo.png
  favicon: /img/sfu_favicon.png
  site-url: https://rcss24.netlify.app/
  repo-url: https://github.com/WestDRI/rcss24
  page-navigation: true
  page-footer:
    center:
      - text: About
        href: about.qmd
      - text: Calendar
        href: calendar.qmd
        aria-label: WestDRI training calendar
      - text: Newsletter
        href: newsletter.qmd
        aria-label: WestDRI Newsletter
      - href: contact.qmd
        aria-label: WestDRI Contact
      - text: Wiki
        href: https://docs.alliancecan.ca/wiki/Technical_documentation
    right:
      - icon: github
        href: https://github.com/WestDRI
        aria-label: WestDRI GitHub
      - icon: youtube
        href: https://www.youtube.com/channel/UCfgds4Qf7VFOv4ORRvFFmhw
        aria-label: WestDRI YouTube
  navbar:
    background: light
    logo: /img/sfudrac_logo.png
    logo-alt: "SFU & DRAC logos"
    title: false
    left:
      - text: Bash
        href: bash.qmd
      - text: HPC
        href: hpc.qmd
      - text: Git
        href: git.qmd
      - text: Intro to Python
        href: pythonintro.qmd
      - text: Scientific Python
        href: pythonscientific.qmd
      - text: High-performance Python
        href: pythonhpc.qmd

format:
  html:
    toc: true
    toc-title: "<em>On this page:</em>"
    toc-depth: 5
    highlight-style: vim-dark
    theme:
      light: [cosmo, theme.scss]
    css: styles.css
    link-external-newwindow: true
    reference-location: margin
    fig-cap-location: margin
    callout-icon: false

execute:
  freeze: auto
  cache: true
  error: true
  echo: true
